#!/usr/bin/env python3
"""
Oncology Pipeline Analyst (Tavily Edition)
基于 Tavily Search API 的早期肿瘤管线价值评估工具

Usage:
    python tavily_research.py <drug_name> [--output OUTPUT]

Examples:
    python tavily_research.py "Enhertu"
    python tavily_research.py "ORIC-944" --output custom_report.json
"""

import asyncio
import os
import sys
from pathlib import Path
from typing import Dict, Any

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from src.research.executor import TavilyResearchExecutor
from src.report.factory import save_search_data, save_report, save_report_from_file
from src.utils.logger import Logger


async def run_research(
    drug_name: str,
    verbose: bool = True
) -> Dict[str, Any]:
    """
    Execute research for a drug

    Args:
        drug_name: Name of the drug to research
        verbose: Whether to print progress information

    Returns:
        Research results dictionary with search context
    """
    logger = Logger(verbose=verbose)

    # Check API keys
    tavily_key = os.getenv('TAVILY_API_KEY')

    if not tavily_key:
        logger.error("TAVILY_API_KEY not set. Please set it in your environment or .env file.")
        sys.exit(1)

    # Initialize executor
    try:
        executor = TavilyResearchExecutor(
            tavily_api_key=tavily_key,
            verbose=verbose
        )
    except Exception as e:
        logger.error(f"Failed to initialize research executor: {e}")
        sys.exit(1)

    # Execute research
    try:
        result = await executor.execute_research(drug_name)
        return result
    except Exception as e:
        logger.error(f"Research failed: {e}")
        raise


def main():
    """Main entry point"""
    import argparse

    parser = argparse.ArgumentParser(
        description='Oncology Pipeline Analyst (Tavily Edition)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python tavily_research.py "Enhertu"
  python tavily_research.py "ORIC-944" --output custom_report.json
        """
    )

    parser.add_argument('drug', help='Drug name to research')
    parser.add_argument(
        '--output', '-o',
        help='Output file path (optional)'
    )
    parser.add_argument(
        '--output-dir',
        help='Output directory for generated files (default: current directory)'
    )
    parser.add_argument(
        '--quiet', '-q',
        action='store_true',
        help='Suppress non-error output'
    )

    args = parser.parse_args()

    verbose = not args.quiet

    # Print header
    if verbose:
        print("=" * 60)
        print("Oncology Pipeline Analyst (Tavily Edition)")
        print("=" * 60)
        print(f"Drug: {args.drug}")
        print(f"Mode: 6-Round Deep Search")
        print("=" * 60)

    # Run research
    try:
        result = asyncio.run(run_research(args.drug, verbose=verbose))

        # Save search data (JSON only)
        if verbose:
            print("\n" + "=" * 60)
            print("Saving search data...")

        generated_files = save_search_data(result, args.output, output_dir=args.output_dir)

        if verbose:
            print("=" * 60)
            print("Search Complete!")
            print(f"Sources found: {result.get('sources_count', 0)}")
            print("\nGenerated files:")
            for fmt, path in generated_files.items():
                print(f"  [{fmt.upper()}] {path}")
            print("=" * 60)
            print("\nSearch data saved. Report will be generated by the calling model.")
            print("JSON path: " + generated_files.get('json', 'N/A'))

    except KeyboardInterrupt:
        print("\n\n[INFO] Research interrupted by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n[ERROR] {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
