"""Report factory for creating different report formats"""

import json
import time
from pathlib import Path
from typing import Dict, Any, Optional

from .markdown_report import MarkdownReport
from .pdf_report import generate_pdf


def save_search_data(results: Dict[str, Any], output_path: Optional[str] = None,
                     output_dir: Optional[str] = None) -> Dict[str, str]:
    """Save search results as JSON only (no report content yet)

    Args:
        results: Research results dictionary
        output_path: Optional custom output path
        output_dir: Optional output directory

    Returns:
        Dictionary with path to generated JSON file
    """
    drug_name = results.get('drug_name', 'unknown')
    mode = results.get('mode', 'research')
    timestamp = str(int(time.time()))

    if output_path:
        base_path = Path(output_path).stem
    else:
        base_path = f"{mode}_{drug_name}_{timestamp}"

    if output_dir:
        out = Path(output_dir)
    elif output_path:
        out = Path(output_path).parent
    else:
        out = Path('.')

    out.mkdir(parents=True, exist_ok=True)

    generated_files = {}

    # Save JSON
    json_path = out / f"{base_path}.json"
    json_path.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding='utf-8')
    generated_files['json'] = str(json_path)

    return generated_files


def save_report(report_content: str, results: Dict[str, Any],
                output_dir: Optional[str] = None) -> Dict[str, str]:
    """Save model-generated report as MD and PDF

    Args:
        report_content: The report text generated by the model
        results: Original research results dictionary (for metadata)
        output_dir: Optional output directory

    Returns:
        Dictionary with paths to generated files
    """
    drug_name = results.get('drug_name', 'unknown')
    mode = results.get('mode', 'research')
    timestamp = str(int(time.time()))
    base_path = f"{mode}_{drug_name}_{timestamp}"

    if output_dir:
        out = Path(output_dir)
    else:
        out = Path('.')

    out.mkdir(parents=True, exist_ok=True)

    # Inject report content into results for report generators
    results_with_report = {**results, 'report': report_content}

    generated_files = {}

    # Save Markdown
    try:
        md_report = MarkdownReport(results_with_report)
        md_path = out / f"{base_path}.md"
        md_report.save(md_path)
        generated_files['markdown'] = str(md_path)
    except Exception as e:
        print(f"[WARN] Markdown generation failed: {e}")

    # Save PDF
    try:
        pdf_path = out / f"{base_path}.pdf"
        pdf_result = generate_pdf(results_with_report, str(pdf_path))
        if pdf_result:
            generated_files['pdf'] = pdf_result
    except Exception as e:
        print(f"[WARN] PDF generation failed: {e}")

    return generated_files


def save_report_from_file(report_file: str, json_file: str,
                          output_dir: Optional[str] = None) -> Dict[str, str]:
    """Save report from a markdown file and JSON search data

    Args:
        report_file: Path to the markdown report file written by the model
        json_file: Path to the JSON search data file
        output_dir: Optional output directory

    Returns:
        Dictionary with paths to generated files
    """
    import json as json_mod

    report_content = Path(report_file).read_text(encoding='utf-8')

    with open(json_file, encoding='utf-8') as f:
        results = json_mod.load(f)

    return save_report(report_content, results, output_dir=output_dir)
